version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true

clone_depth: 1

init:
- cmd: echo %Platform% %Configuration%

install:
- sh: sudo apt-get update -qy
- sh: sudo apt-get install -qy clang libc++-dev libc++abi-dev
- cmd: .appveyor\prepare-prebuilt-v8.cmd
- sh: make get-prebuilt-v8
- cmd: ensure_dependencies.py
- sh: python ensure_dependencies.py

environment:
  global:
    URL_PREFIX: https://v8.eyeofiles.com/v8-9a7be49a7a6e435d8a7d435c4879340a3cc7524c/
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: ubuntu1804
    Configuration: Debug
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x64
    Configuration: Release
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x64
    Configuration: Debug
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: Win32
    Configuration: Release
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: Win32
    Configuration: Debug

before_build:
- cmd: set "GYP_DEFINES=libv8_include_dir=third_party/prebuilt-v8/include libv8_lib_dir=../../third_party/prebuilt-v8 libv8_show_warnings=true"
- cmd: createsolution.bat
- cmd: >-
    if "%Platform%"=="Win32" set arch="ia32"

    if "%Platform%"=="x64" set arch="x64"

build_script:
- cmd: msbuild "build/%arch%/tests.sln" /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cmd: msbuild "build/%arch%/abpshell.sln" /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- sh: make
test_script:
- cmd: build\%arch%\%Configuration%\tests.exe --gtest_output=xml:tests.xml
- sh: ./build/out/Debug/tests --gtest_output=xml:tests.xml
after_test:
- ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))
deploy: off
